Repository charmbracelet/huh, pull requests merged in 2024-08, with the labels that each got.

#335 fix: set filterable not working on multi select
  field_multiselect.go
  huh_test.go
Labels: bug

#362 fix(deps): remove x/exp/term
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  huh_test.go
Labels: bug

#363 fix: group size when height is 0
  field_input.go
  group.go
Labels: bug

#378 fix: golangci-lint issues
  .golangci-soft.yml
  field_text.go
  form.go
  group.go
  layout.go
Labels: enhancement

#380 chore: bump charmbracelet/x dependencies
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: dependencies
