Repository charmbracelet/huh, pull requests merged in 2025-03, with the labels that each got.

#546 chore(deps): update bubbletea, catppuccin
  .github/workflows/build.yml
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: dependencies

#503 feat: expose focused field
  form.go
  huh_test.go
Labels: enhancement

#347 docs: add example of Dynamic Huh? inside Bubble Tea application
  examples/dynamic/dynamic-bubbletea/main.go
Labels: documentation

#505 fix rendering of dynamic fields in groups
  group.go
Labels: bug

#567 fix: form and group styles
  form.go
  group.go
  theme.go
Labels: enhancement

#569 fix(select,multiselect): multi line items, scrolling
  field_multiselect.go
  field_select.go
  huh_test.go
Labels: bug, select, multiselect

#570 fix: wrap titles and descriptions when needed
  examples/go.mod
  examples/go.sum
  examples/issue-519/main.go
  field_confirm.go
  field_filepicker.go
  field_input.go
  field_multiselect.go
  field_note.go
  field_select.go
  field_text.go
  go.mod
  go.sum
  group.go
  wrap.go
Labels: bug

#581 ci: lint settings and fixes
  .github/workflows/lint-soft.yml
  .github/workflows/lint-sync.yml
  .golangci-soft.yml
  .golangci.yml
  field_filepicker.go
  field_multiselect.go
  field_select.go
Labels: enhancement

#593 fix(filepicker): height, navigation
  field_filepicker.go
  keymap.go
Labels: bug, filepicker
